package lei.buaa.leidrib.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IMAGES".
 */
public class Images {

    private Long id;
    private String hidpi;
    private String normal;
    private String teaser;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Images() {
    }

    public Images(Long id) {
        this.id = id;
    }

    public Images(Long id, String hidpi, String normal, String teaser) {
        this.id = id;
        this.hidpi = hidpi;
        this.normal = normal;
        this.teaser = teaser;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHidpi() {
        return hidpi;
    }

    public void setHidpi(String hidpi) {
        this.hidpi = hidpi;
    }

    public String getNormal() {
        return normal;
    }

    public void setNormal(String normal) {
        this.normal = normal;
    }

    public String getTeaser() {
        return teaser;
    }

    public void setTeaser(String teaser) {
        this.teaser = teaser;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
